### PR TITLE
Adding the Kompsat and Paz IDs (kxs) for GMAO ingestion of FSOI data

### LINKED ISSUE #168: Unknown platforms are being reported when ingesting GMAO FSOI data
## Description
Unknown platforms are being reported when ingesting GMAO FSOI data. This started on March 5, 2022, with the following message:
```
Unknown platform attribute encountered while processing files from GMAO. Unknown platform ID(s): 44, 825, file timestamp : 2022030200
```
This is probably related to the latest upgrade o GMAO's GEOS-FP system, more information can be found here: https://gmao.gsfc.nasa.gov/GMAO_products/NRT_products.php.

## Acceptance Criteria (Definition of Done)
No unknown platforms are reported.

## Dependencies
None

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Description
This PR is adding the Kompsat and Paz IDs (kx) for GMAO ingestion of FSOI data.

### Issue(s) addressed
- fixes #168

## Acceptance Criteria (Definition of Done)
No "unknown" platforms are reported when decoding GMAO FSOI data.

## Dependencies
None

## Impact
None

### CODE REVIEW

**Comment by fabiolrdiniz** [comment]
For some reason, this PR is failing CI tests here. I see this in the log, but not clear why because this PR is not changing that:
```
Collecting tables
--
159 | Downloading https://files.pythonhosted.org/packages/d2/55/fb95c1c82750f05eb0fd082cc95c25f56cc32a4fd3518794cce1914af1ff/tables-3.7.0.tar.gz (8.2MB)
160 | Installing build dependencies: started
161 | Installing build dependencies: finished with status 'done'
162 | Getting requirements to build wheel: started
163 | Getting requirements to build wheel: finished with status 'error'
164 | ERROR: Command errored out with exit status 1:
165 | command: /opt/python/bin/python3.8 /opt/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpogu40kll
166 | cwd: /tmp/pip-install-40suiqv8/tables
167 | Complete output (14 lines):
168 | /tmp/H5close2gxp8cvt.c: In function ‘main’:
169 | /tmp/H5close2gxp8cvt.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
170 | H5close();
171 | ^~~~~~~
172 | /usr/bin/ld: cannot find -lhdf5
173 | collect2: error: ld returned 1 exit status
174 | cpuinfo failed, assuming no CPU features: No module named 'cpuinfo'
175 | * Using Python 3.8.3rc1 (default, May  1 2020, 20:57:46)
176 | * Found cython 0.29.28
177 | * USE_PKGCONFIG: True
178 | .. ERROR:: Could not find a local HDF5 installation.
179 | You may need to explicitly state where your local HDF5 headers and
180 | library can be found by setting the ``HDF5_DIR`` environment
181 | variable or by using the ``--hdf5`` command-line option.
182 | ----------------------------------------
183 | ERROR: Command errored out with exit status 1: /opt/python/bin/python3.8 /opt/python/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpogu40kll Check the logs for full command output.
184 | WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
185 | You should consider upgrading via the 'pip install --upgrade pip' command.
186 | make: *** [Makefile:11: aws_lambda] Error 1
```

**Review by hahnd — APPROVED** [review]
The build problem was caused by a new version of the _tables_ python library when building the AWS lambda artifact.  I updated the Makefile to use explicit versions of required python libraries to resolve this issue and avoid other similar issues in the future.

The alternative solution would be to continue using the latest python libraries and update the docker container as errors come up.  In this case, _tables_ was looking for the _HDF5_ library in the container in order to be installed.

**Comment by fabiolrdiniz** [comment]
Thank you so much for checking this @hahnd!

**Review by fcvdb — APPROVED** [review]
Thanks Fabio and David.

**Pull request merged**
